version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GATEWAY_API_URL=https://api-gateway-production-1b48.up.railway.app
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 